site_name: G.algos
site_url: https://g-algos.com

theme:
  name: material
  palette:
    primary: deep purple
    accent: yellow
  font:
    text: Comfortaa
  favicon: assets/GA.png
  logo: assets/Galgo_32.svg
  custom_dir: overrides
  icon:
    logo: Galgo_32.svg
extra_css:
  - assets/css/custom.css
nav:
  - Intro: index.md
  - G.plus:
      - Overview: G.plus/Intro.md
      - Data Links: G.plus/DataLinks.md
      - Location Schemes: G.plus/LocalizationSchemas.md
      - File Version: G.plus/FileVersioning.md
      - Releases: G.plus/changelog.md
      - Privacy Policy: G.plus/PrivacyPolicy.md
  - BDS:
      - Overview: BDS/Intro.md
      - Scheme: BDS/Scheme.md
  - G.BDS.Manager:
      - Overview: G.BDS.Manager/Intro.md
      - Main Features: G.BDS.Manager/MainFeatures.md
plugins:
  - search
  - meta
  - include-markdown
  - macros

watch:
  - layouts
